/**
 * Tests for the workerd backend bundler.
 *
 * These are not mocked — they invoke esbuild against the real playground
 * fixtures, then either inspect the produced bundle text or import it as
 * an ESM module to exercise the workerd `default.fetch(...)` entrypoint.
 *
 * One esbuild worker is shared across the whole file because esbuild's
 * `stop()` is process-global; we tear it down once in a final
 * `t.step`-shaped cleanup test. Per-test sanitizer suppression is needed
 * because that worker is a child process that outlives individual tests.
 *
 * The "env shim works at runtime" assertion lives in the workerd e2e test
 * (M1) — under host Deno, `globalThis.Deno` is read-only and our shim
 * deliberately defers to it, so the contract can only be exercised inside
 * a real workerd process.
 */

import { assert, assertEquals, assertRejects, assertStringIncludes } from "@std/assert";
import { join, resolve as resolvePath } from "node:path";
import { pathToFileURL } from "node:url";
import * as esbuild from "esbuild";
import {
  type Bundler,
  createBundler,
  discoverEntrypoints,
  discoverSharedModules,
} from "../src/backends/workerd/bundler.ts";

const PROJECT_ROOT = resolvePath(new URL("..", import.meta.url).pathname.replace(/^\/(\w:)/, "$1"));
const PLAYGROUND = join(PROJECT_ROOT, "playground");
const DENO_JSON = join(PROJECT_ROOT, "deno.json");

// Single bundler per process — esbuild's worker is global. Each test gets
// its own outDir so results don't collide.
let _shared: Bundler | null = null;
function sharedBundler(outDir: string): Bundler {
  if (!_shared) {
    _shared = createBundler({ outDir, configPath: DENO_JSON });
    return _shared;
  }
  // Re-create with a different outDir but reuse esbuild's global state by
  // not calling stop on the old one. The factory is cheap (closures only).
  return createBundler({ outDir, configPath: DENO_JSON });
}

async function makeOutDir(label: string): Promise<string> {
  return await Deno.makeTempDir({ prefix: `1tube-bundler-${label}-` });
}

async function importBundle(bundlePath: string): Promise<{
  fetch: (req: Request, env?: Record<string, string>, ctx?: unknown) => Promise<Response>;
}> {
  // Cache-bust on every import so a rebuilt bundle isn't shadowed by a
  // stale module from a previous test in the same process.
  const url = pathToFileURL(bundlePath).href + `?v=${crypto.randomUUID()}`;
  const mod = await import(url);
  return mod.default;
}

const BUNDLER_TEST = {
  sanitizeResources: false,
  sanitizeOps: false,
} as const;

Deno.test("workerd-bundler: bundles a public function and runs it", BUNDLER_TEST, async () => {
  const outDir = await makeOutDir("hello");
  try {
    const bundler = sharedBundler(outDir);
    const result = await bundler.bundle({
      name: "hello",
      entrypoint: join(PLAYGROUND, "hello", "index.ts"),
    });

    assertEquals(result.name, "hello");
    assert(result.byteLength > 0, "bundle should not be empty");
    assert(result.bundlePath.endsWith("hello.js"));
    assertEquals(result.sourcemapPath, `${result.bundlePath}.map`);

    const text = await Deno.readTextFile(result.bundlePath);
    assertStringIncludes(text, "AUTO-GENERATED by 1tube workerd bundler");
    assertStringIncludes(text, "__edgeFunctionRegistry");
    assertStringIncludes(text, "export default");

    const handler = await importBundle(result.bundlePath);
    const res = await handler.fetch(
      new Request("http://localhost/functions/v1/hello"),
      {},
    );
    assertEquals(res.status, 200);
    const body = await res.json();
    assert(typeof body.message === "string");
  } finally {
    await Deno.remove(outDir, { recursive: true });
  }
});

Deno.test("workerd-bundler: bundles echo and round-trips a JSON body", BUNDLER_TEST, async () => {
  const outDir = await makeOutDir("echo");
  try {
    const bundler = sharedBundler(outDir);
    const result = await bundler.bundle({
      name: "echo",
      entrypoint: join(PLAYGROUND, "echo", "index.ts"),
    });
    const handler = await importBundle(result.bundlePath);

    const req = new Request("http://localhost/functions/v1/echo?x=1", {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ hello: "workerd" }),
    });
    const res = await handler.fetch(req, {});
    assertEquals(res.status, 200);
    const body = await res.json() as {
      method: string;
      query: Record<string, string>;
      body: { hello: string };
    };
    assertEquals(body.method, "POST");
    assertEquals(body.query.x, "1");
    assertEquals(body.body.hello, "workerd");
  } finally {
    await Deno.remove(outDir, { recursive: true });
  }
});

Deno.test("workerd-bundler: authenticated handler sees the auth headers", BUNDLER_TEST, async () => {
  const outDir = await makeOutDir("whoami");
  try {
    const bundler = sharedBundler(outDir);
    const result = await bundler.bundle({
      name: "whoami",
      entrypoint: join(PLAYGROUND, "whoami", "index.ts"),
    });
    const handler = await importBundle(result.bundlePath);

    const req = new Request("http://localhost/functions/v1/whoami", {
      headers: {
        "X-1tube-Auth-User": "user-42",
        "X-1tube-Auth-Email": "user@example.com",
        "X-1tube-Auth-Token": "tok",
        "X-1tube-Auth-Payload": JSON.stringify({ role: "authenticated" }),
      },
    });
    const res = await handler.fetch(req, {});
    assertEquals(res.status, 200);
    const body = await res.json() as {
      userId: string;
      email: string;
      payload: { role: string };
    };
    assertEquals(body.userId, "user-42");
    assertEquals(body.email, "user@example.com");
    assertEquals(body.payload.role, "authenticated");
  } finally {
    await Deno.remove(outDir, { recursive: true });
  }
});

Deno.test("workerd-bundler: emits the Deno.env shim verbatim into the bundle", BUNDLER_TEST, async () => {
  // Runtime behaviour of the shim is exercised by the e2e workerd test;
  // here we only assert the bundler emits the contract the e2e test
  // relies on, since under host Deno the real `globalThis.Deno` shadows
  // the shim by design.
  const outDir = await makeOutDir("env-shim");
  try {
    const bundler = sharedBundler(outDir);
    const result = await bundler.bundle({
      name: "hello",
      entrypoint: join(PLAYGROUND, "hello", "index.ts"),
    });
    const text = await Deno.readTextFile(result.bundlePath);
    assertStringIncludes(text, "__1tubeWorkerEnv");
    assertStringIncludes(text, "__1tubeDenoEnv");
    assertStringIncludes(text, "globalThis.__edgeFunctionRegistry");
    assertStringIncludes(text, 'typeof Deno === "undefined"');
    assertStringIncludes(text, 'Object.defineProperty(globalThis, "Deno"');
  } finally {
    await Deno.remove(outDir, { recursive: true });
  }
});

Deno.test("workerd-bundler: shared modules are replaced with RPC stubs", BUNDLER_TEST, async () => {
  const root = await Deno.makeTempDir({ prefix: "1tube-shared-fixture-" });
  const outDir = await makeOutDir("shared-stub");
  try {
    await Deno.mkdir(join(root, "_shared"), { recursive: true });
    await Deno.mkdir(join(root, "needs-profile"), { recursive: true });
    await Deno.writeTextFile(
      join(root, "_shared", "profile-cache.ts"),
      `const cache = new Map([["u1", { claims: ["teacher"] }]]);
export async function getCachedProfile(userId: string) {
  return cache.get(userId) ?? { claims: [] };
}
export function invalidateProfile(userId: string) {
  cache.delete(userId);
}
`,
    );
    await Deno.writeTextFile(
      join(root, "_shared", "handler.ts"),
      `export function serve(handler: (req: Request) => Response | Promise<Response>) {
  (globalThis as any).__edgeFunctionRegistry.register(handler, { public: true });
}
`,
    );
    await Deno.writeTextFile(
      join(root, "needs-profile", "index.ts"),
      `import { serve } from "../_shared/handler.ts";
import { getCachedProfile } from "../_shared/profile-cache.ts";
serve(async () => Response.json(await getCachedProfile("u1")));
`,
    );

    const sharedModules = await discoverSharedModules(root);
    const bundler = createBundler({ outDir, sharedModules, sourcemap: false });
    const result = await bundler.bundle({
      name: "needs-profile",
      entrypoint: join(root, "needs-profile", "index.ts"),
    });
    const text = await Deno.readTextFile(result.bundlePath);
    assertStringIncludes(text, "/modules/");
    assertStringIncludes(text, "/call/");
    assertStringIncludes(text, "getCachedProfile");
    assert(!text.includes("new Map([[\"u1\""), "real shared module must not be bundled into isolate");
  } finally {
    await Deno.remove(root, { recursive: true }).catch(() => {});
    await Deno.remove(outDir, { recursive: true }).catch(() => {});
  }
});

Deno.test("workerd-bundler: produces deterministic output for identical input", BUNDLER_TEST, async () => {
  const outA = await makeOutDir("det-a");
  const outB = await makeOutDir("det-b");
  try {
    const bundlerA = sharedBundler(outA);
    const bundlerB = sharedBundler(outB);
    const a = await bundlerA.bundle({
      name: "hello",
      entrypoint: join(PLAYGROUND, "hello", "index.ts"),
    });
    const b = await bundlerB.bundle({
      name: "hello",
      entrypoint: join(PLAYGROUND, "hello", "index.ts"),
    });
    const textA = await Deno.readTextFile(a.bundlePath);
    const textB = await Deno.readTextFile(b.bundlePath);
    assertEquals(textA, textB, "identical inputs should yield byte-identical bundles");
  } finally {
    await Deno.remove(outA, { recursive: true });
    await Deno.remove(outB, { recursive: true });
  }
});

Deno.test("workerd-bundler: bundleAll fans out and returns one result per input", BUNDLER_TEST, async () => {
  const outDir = await makeOutDir("all");
  try {
    const bundler = sharedBundler(outDir);
    const inputs = await discoverEntrypoints(PLAYGROUND);
    assert(inputs.length >= 2, `expected >=2 playground fns, got ${inputs.length}`);

    const results = await bundler.bundleAll(inputs, { concurrency: 2 });
    assertEquals(results.length, inputs.length);
    for (const r of results) {
      assert(r.byteLength > 0);
      const stat = await Deno.stat(r.bundlePath);
      assert(stat.isFile);
    }
    const names = results.map((r) => r.name);
    assertEquals([...names].sort(), names);
  } finally {
    await Deno.remove(outDir, { recursive: true });
  }
});

Deno.test("workerd-bundler: reports a useful error for a broken entrypoint", BUNDLER_TEST, async () => {
  const fnDir = await Deno.makeTempDir({ prefix: "1tube-bundler-bad-fn-" });
  try {
    await Deno.writeTextFile(
      join(fnDir, "index.ts"),
      `import { somethingThatDoesNotExist } from "./nope.ts";\n` +
        `console.log(somethingThatDoesNotExist);\n`,
    );

    const outDir = await makeOutDir("bad");
    try {
      const bundler = sharedBundler(outDir);
      // esbuild itself throws an aggregate `Error: Build failed with N error(s)`
      // when bundle() encounters errors with `logLevel: silent`. We don't
      // wrap that — surfacing the original message preserves location info.
      // The assertion just confirms the error mentions the missing module.
      await assertRejects(
        () => bundler.bundle({ name: "bad", entrypoint: join(fnDir, "index.ts") }),
        Error,
        "nope.ts",
      );
    } finally {
      await Deno.remove(outDir, { recursive: true });
    }
  } finally {
    await Deno.remove(fnDir, { recursive: true });
  }
});

Deno.test("workerd-bundler: discoverEntrypoints skips _shared and underscored dirs", BUNDLER_TEST, async () => {
  const inputs = await discoverEntrypoints(PLAYGROUND);
  for (const i of inputs) {
    assert(!i.name.startsWith("_"), `should skip underscored dir: ${i.name}`);
    assert(!i.name.endsWith("_shared"), `should skip *_shared dir: ${i.name}`);
  }
  for (const i of inputs) {
    const stat = await Deno.stat(i.entrypoint);
    assert(stat.isFile);
  }
});

// MUST be the last test in the file — esbuild's worker is global and
// stop() is one-shot. Running this earlier would tear down the worker
// other tests still need.
Deno.test("workerd-bundler: shutdown releases the esbuild worker", BUNDLER_TEST, async () => {
  await esbuild.stop();
  _shared = null;
});
