/**
 * workerd bundle profile.
 *
 * Owns the workerd-specific banner/footer and esbuild resolution settings that
 * the target-agnostic bundler core consumes through a {@link BundleProfile}.
 *
 * The banner installs, before any user code runs:
 *
 *  1. **`Deno.env` shim.** User code reads env via `Deno.env.get(...)`. workerd
 *     injects environment as the per-request `env` binding instead. The banner
 *     installs a `globalThis.Deno.env` proxy that reads from a module-scope
 *     variable refreshed on every dispatch.
 *
 *  2. **`serve()` registry shim.** The 1tube `_shared/handler.ts` shim looks for
 *     `globalThis.__edgeFunctionRegistry` and registers its handler there at
 *     import time. The banner supplies a tiny single-handler registry so the
 *     existing shim works unchanged.
 *
 *  3. **Console capture.** Each `console.*` call is serialised as one marked
 *     JSON line so the gateway's log sink can attribute it to the invocation.
 *
 * The footer exports a workerd `default { fetch(req, env, ctx) }` that dispatches
 * to whatever the module registered, reconstructing the `AuthContext` from the
 * trusted `X-1tube-Auth-*` headers the gateway forwards.
 */

import type { BundleProfile } from "../../bundler/profile.ts";

/**
 * Banner injected at the top of every bundle. Runs before any user code so
 * top-level `serve(...)` calls find a registry to register against.
 *
 * The captured handler/options live in module scope; the footer below exports
 * the workerd default fetch handler that calls into them.
 *
 * `__1tubeWorkerEnv` is refreshed by the footer on every fetch so
 * `Deno.env.get()` returns the right values for that invocation. workerd doesn't
 * change `env` per-request in practice (it's bound at boot), but pinning it on
 * each call makes the contract robust to future bindings.
 */
const WORKERD_BANNER = `// AUTO-GENERATED by 1tube workerd bundler — do not edit
import { AsyncLocalStorage as __1tubeAsyncLocalStorage } from "node:async_hooks";
let __1tubeCapturedHandler;
let __1tubeCapturedOpts = { public: false };
let __1tubeWorkerEnv = {};

// ---------------------------------------------------------------------------
// Console capture.
//
// workerd has no message channel back to the gateway, but its stdout is
// already pumped line-by-line into the gateway process. Each console
// call is serialized as ONE marked JSON line; the gateway's log sink
// (src/logs/console-marker.ts) parses marked lines into structured log
// rows and prints the plain message for the operator. The footer runs
// every dispatch inside __1tubeInvocationCtx so concurrent requests
// attribute their lines correctly.
// ---------------------------------------------------------------------------
const __1tubeInvocationCtx = new __1tubeAsyncLocalStorage();
const __1tubeLogMarker = "__1TUBE_LOG__";
const __1tubeRawConsoleLog = console.log.bind(console);
// Like the Deno shim below: only take over console under real workerd.
// When a bundle is imported into a host Deno realm (1tube's own tests)
// the test runner's console must stay untouched.
const __1tubeConsoleCaptureActive = typeof Deno === "undefined";

function __1tubeFormatArg(a) {
  if (typeof a === "string") return a;
  if (a instanceof Error) return a.stack || (a.name + ": " + a.message);
  try {
    const s = JSON.stringify(a);
    if (typeof s === "string") return s;
  } catch { /* circular / bigint — fall through */ }
  try { return String(a); } catch { return "[unprintable]"; }
}

function __1tubeEmitConsole(level, args) {
  if (!__1tubeConsoleCaptureActive) {
    __1tubeRawConsoleLog(...args);
    return;
  }
  try {
    let msg = args.map(__1tubeFormatArg).join(" ");
    if (msg.length > 8192) msg = msg.slice(0, 8192) + "…";
    __1tubeRawConsoleLog(__1tubeLogMarker + JSON.stringify({
      id: __1tubeInvocationCtx.getStore()?.invocationId ?? null,
      level,
      msg,
      ts: Date.now(),
    }));
  } catch { /* capture must never break user code */ }
}

if (__1tubeConsoleCaptureActive) {
  for (const __1tubeLevel of ["debug", "log", "info", "warn", "error"]) {
    console[__1tubeLevel] = (...args) => __1tubeEmitConsole(__1tubeLevel, args);
  }
}

const __1tubeRegistry = {
  register(handler, opts) {
    __1tubeCapturedHandler = handler;
    __1tubeCapturedOpts = { public: !!opts?.public, timeoutMs: opts?.timeoutMs };
  },
};

const __1tubeDenoEnv = {
  get(key) {
    const v = __1tubeWorkerEnv?.[key];
    if (typeof v === "string") return v;
    const pv = globalThis.process?.env?.[key];
    return typeof pv === "string" ? pv : undefined;
  },
  set() {
    throw new Error("Deno.env.set is not supported under the workerd backend");
  },
  delete() {
    throw new Error("Deno.env.delete is not supported under the workerd backend");
  },
  has(key) {
    return typeof __1tubeWorkerEnv?.[key] === "string" ||
      typeof globalThis.process?.env?.[key] === "string";
  },
  toObject() {
    const out = {};
    for (const k of Object.keys(globalThis.process?.env ?? {})) {
      const v = globalThis.process.env[k];
      if (typeof v === "string") out[k] = v;
    }
    for (const k of Object.keys(__1tubeWorkerEnv ?? {})) {
      const v = __1tubeWorkerEnv[k];
      if (typeof v === "string") out[k] = v;
    }
    return out;
  },
};

// __edgeFunctionRegistry is *always* replaced with this bundle's own
// instance. Each bundle has its own module-scope \`__1tubeCapturedHandler\`,
// so the registry's \`register()\` must close over THIS bundle's locals —
// even if a previous import (e.g. when several bundles are imported into
// the same Deno realm during tests) already installed its own.
globalThis.__edgeFunctionRegistry = __1tubeRegistry;

// Install the \`Deno\` shim only when there is no host Deno — i.e. we're
// running under real workerd. Under host Deno (e.g. when 1tube's own
// test suite imports a bundle to verify the bundler) we deliberately
// leave the host's \`Deno\` global untouched: replacing it would break
// the test runner's own use of Deno.makeTempDir / Deno.readDir / etc.
// The runtime contract for the env shim is exercised by the workerd
// end-to-end test, which runs inside an actual workerd process where
// \`typeof Deno === "undefined"\`.
if (typeof Deno === "undefined") {
  Object.defineProperty(globalThis, "Deno", {
    value: {
      env: __1tubeDenoEnv,
      // Defence in depth: a stray top-level Deno.serve(...) becomes a
      // no-op instead of a ReferenceError. The registry is the supported
      // path; this just keeps the failure mode quiet.
      serve: () => ({
        finished: Promise.resolve(),
        shutdown: () => {},
        ref: () => {},
        unref: () => {},
      }),
    },
    writable: true,
    configurable: true,
    enumerable: false,
  });
}
`;

/**
 * Footer injected at the bottom of every bundle. Exports the workerd default
 * handler. Authentication is the gateway's job; this just rebuilds the
 * AuthContext from the trusted internal headers the gateway forwards.
 */
const WORKERD_FOOTER = `
function __1tubeBuildAuth(request) {
  const h = request.headers;
  const payloadRaw = h.get("X-1tube-Auth-Payload");
  let payload = {};
  if (payloadRaw) {
    try { payload = JSON.parse(payloadRaw); } catch { payload = {}; }
  }
  return {
    userId: h.get("X-1tube-Auth-User") || "anon",
    email: h.get("X-1tube-Auth-Email") || "",
    rawToken: h.get("X-1tube-Auth-Token") || "",
    payload,
  };
}

export default {
  async fetch(request, env, _ctx) {
    __1tubeWorkerEnv = env || {};
    if (typeof __1tubeCapturedHandler !== "function") {
      return new Response(
        JSON.stringify({ error: "function did not register a handler" }),
        { status: 500, headers: { "content-type": "application/json" } },
      );
    }
    // Invocation id stamped by the gateway before proxying. Binds this
    // dispatch's console output (see the banner's console shim) to the
    // invocation row the gateway persists.
    const __1tubeInvocationId = request.headers.get("x-1tube-invocation-id");
    const __1tubeRun = async () => {
      if (__1tubeCapturedOpts.public) {
        return await __1tubeCapturedHandler(request);
      }
      return await __1tubeCapturedHandler(request, __1tubeBuildAuth(request));
    };
    try {
      return await __1tubeInvocationCtx.run(
        { invocationId: __1tubeInvocationId },
        __1tubeRun,
      );
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      // Surface the stack through the capture channel so the log store
      // keeps it next to the invocation that threw.
      __1tubeInvocationCtx.run({ invocationId: __1tubeInvocationId }, () => {
        __1tubeEmitConsole("error", [err instanceof Error ? (err.stack || msg) : msg]);
      });
      return new Response(
        JSON.stringify({ error: msg }),
        { status: 500, headers: { "content-type": "application/json" } },
      );
    }
  },
};
`;

/**
 * Bundle profile for the workerd backend. Resolves the leaner `worker`/`browser`
 * package builds under a `neutral` platform (workerd provides builtins via its
 * own `nodejs_compat`, reached through `node:` specifiers).
 */
export const WORKERD_PROFILE: BundleProfile = {
  id: "workerd",
  platform: "neutral",
  conditions: ["worker", "browser", "import", "default"],
  mainFields: ["module", "main"],
  banner: WORKERD_BANNER,
  footer: WORKERD_FOOTER,
};
