/**
 * Edge-function bundler for the workerd backend.
 *
 * Workerd does not resolve `npm:`, `jsr:`, or `https:` specifiers at runtime
 * — every module must be present on disk as a fully-resolved ESM file before
 * the worker boots. This bundler fills that gap by running esbuild over each
 * function's `index.ts`, with `@luca/esbuild-deno-loader` providing
 * Deno-native specifier resolution. The output is a single self-contained
 * ESM file per function, written to a content-addressed cache directory
 * under the project so repeated boots are fast and reproducible.
 *
 * Each bundle is wrapped to bridge two impedance mismatches:
 *
 *  1. **`Deno.env` shim.** User code reads env via `Deno.env.get(...)`.
 *     Workerd injects environment as the per-request `env` binding instead.
 *     The wrapper installs a `globalThis.Deno.env` proxy that reads from a
 *     module-scope variable refreshed on every dispatch.
 *
 *  2. **`serve()` registry shim.** The 1tube `_shared/handler.ts` shim looks
 *     for `globalThis.__edgeFunctionRegistry` and registers its handler
 *     there at import time. The wrapper supplies a tiny single-handler
 *     registry so the existing shim works unchanged, then exports a workerd
 *     `default { fetch(req, env, ctx) }` that dispatches to whatever the
 *     module registered.
 *
 * The auth boundary stays in 1tube's gateway. For non-public handlers the
 * gateway validates the JWT and forwards the verified identity to workerd
 * via `X-1tube-Auth-*` headers (loopback-only socket). The wrapper
 * reconstructs the `AuthContext` shape from those headers so user code is
 * agnostic to which backend is running.
 *
 * This module is pure I/O orchestration around esbuild. The Deno test
 * suite drives it with real bundles against the playground fixtures —
 * there is no mock layer because esbuild's behaviour is the contract.
 */

import { join, resolve as resolvePath } from "node:path";
import { pathToFileURL } from "node:url";
import { ensureDir } from "jsr:@std/fs@^1/ensure-dir";
import * as esbuild from "esbuild";
import { denoPlugin } from "@deno/esbuild-plugin";

/**
 * Banner injected at the top of every bundle. Runs before any user code so
 * top-level `serve(...)` calls find a registry to register against.
 *
 * The captured handler/options live in module scope; the footer below
 * exports the workerd default fetch handler that calls into them.
 *
 * `__1tubeWorkerEnv` is refreshed by the footer on every fetch so
 * `Deno.env.get()` returns the right values for that invocation. Workerd
 * doesn't change `env` per-request in practice (it's bound at boot), but
 * pinning it on each call makes the contract robust to future bindings.
 */
const BANNER = `// AUTO-GENERATED by 1tube workerd bundler — do not edit
let __1tubeCapturedHandler;
let __1tubeCapturedOpts = { public: false };
let __1tubeWorkerEnv = {};

const __1tubeRegistry = {
  register(handler, opts) {
    __1tubeCapturedHandler = handler;
    __1tubeCapturedOpts = { public: !!opts?.public, timeoutMs: opts?.timeoutMs };
  },
};

const __1tubeDenoEnv = {
  get(key) {
    const v = __1tubeWorkerEnv?.[key];
    return typeof v === "string" ? v : undefined;
  },
  set() {
    throw new Error("Deno.env.set is not supported under the workerd backend");
  },
  delete() {
    throw new Error("Deno.env.delete is not supported under the workerd backend");
  },
  has(key) {
    return typeof __1tubeWorkerEnv?.[key] === "string";
  },
  toObject() {
    const out = {};
    for (const k of Object.keys(__1tubeWorkerEnv ?? {})) {
      const v = __1tubeWorkerEnv[k];
      if (typeof v === "string") out[k] = v;
    }
    return out;
  },
};

// __edgeFunctionRegistry is *always* replaced with this bundle's own
// instance. Each bundle has its own module-scope \`__1tubeCapturedHandler\`,
// so the registry's \`register()\` must close over THIS bundle's locals —
// even if a previous import (e.g. when several bundles are imported into
// the same Deno realm during tests) already installed its own.
globalThis.__edgeFunctionRegistry = __1tubeRegistry;

// Install the \`Deno\` shim only when there is no host Deno — i.e. we're
// running under real workerd. Under host Deno (e.g. when 1tube's own
// test suite imports a bundle to verify the bundler) we deliberately
// leave the host's \`Deno\` global untouched: replacing it would break
// the test runner's own use of Deno.makeTempDir / Deno.readDir / etc.
// The runtime contract for the env shim is exercised by the workerd
// end-to-end test, which runs inside an actual workerd process where
// \`typeof Deno === "undefined"\`.
if (typeof Deno === "undefined") {
  Object.defineProperty(globalThis, "Deno", {
    value: {
      env: __1tubeDenoEnv,
      // Defence in depth: a stray top-level Deno.serve(...) becomes a
      // no-op instead of a ReferenceError. The registry is the supported
      // path; this just keeps the failure mode quiet.
      serve: () => ({
        finished: Promise.resolve(),
        shutdown: () => {},
        ref: () => {},
        unref: () => {},
      }),
    },
    writable: true,
    configurable: true,
    enumerable: false,
  });
}
`;

/**
 * Footer injected at the bottom of every bundle. Exports the workerd
 * default handler. Authentication is the gateway's job; this just rebuilds
 * the AuthContext from the trusted internal headers the gateway forwards.
 */
const FOOTER = `
function __1tubeBuildAuth(request) {
  const h = request.headers;
  const payloadRaw = h.get("X-1tube-Auth-Payload");
  let payload = {};
  if (payloadRaw) {
    try { payload = JSON.parse(payloadRaw); } catch { payload = {}; }
  }
  return {
    userId: h.get("X-1tube-Auth-User") || "anon",
    email: h.get("X-1tube-Auth-Email") || "",
    rawToken: h.get("X-1tube-Auth-Token") || "",
    payload,
  };
}

export default {
  async fetch(request, env, _ctx) {
    __1tubeWorkerEnv = env || {};
    if (typeof __1tubeCapturedHandler !== "function") {
      return new Response(
        JSON.stringify({ error: "function did not register a handler" }),
        { status: 500, headers: { "content-type": "application/json" } },
      );
    }
    try {
      if (__1tubeCapturedOpts.public) {
        return await __1tubeCapturedHandler(request);
      }
      return await __1tubeCapturedHandler(request, __1tubeBuildAuth(request));
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return new Response(
        JSON.stringify({ error: msg }),
        { status: 500, headers: { "content-type": "application/json" } },
      );
    }
  },
};
`;

export interface BundleInput {
  /** Logical function name (used as bundle filename and in capnp config). */
  name: string;
  /** Absolute path to the function's `index.ts` entrypoint. */
  entrypoint: string;
}

export interface BundleResult {
  /** Same as input. */
  name: string;
  /** Absolute path to the produced `.js` bundle. */
  bundlePath: string;
  /** Absolute path to the produced sourcemap, or null when sourcemaps are off. */
  sourcemapPath: string | null;
  /** Bundle byte size — useful for diagnostics and CI assertions. */
  byteLength: number;
  /** Wall-clock time esbuild spent on this function. */
  durationMs: number;
}

export interface BundlerOptions {
  /**
   * Directory to write bundles into. Files are named `<name>.js` (+
   * `<name>.js.map` when `sourcemap` is true). Created if missing.
   */
  outDir: string;
  /**
   * Path to the host project's `deno.json` so esbuild-deno-loader can pick
   * up the import map. Optional — when omitted no import map is applied.
   */
  configPath?: string;
  /**
   * Enable inline sourcemaps (`true`), separate `.map` files (`"linked"`),
   * or disable (`false`). Defaults to `"linked"` for production-style
   * debugging without bloating the bundle.
   */
  sourcemap?: boolean | "linked" | "inline";
  /** Emit minified output. Defaults to false (keeps readable stack traces). */
  minify?: boolean;
}

/** State held by a long-lived bundler so esbuild can be reused across builds. */
export interface Bundler {
  /** Bundle a single function. */
  bundle(input: BundleInput): Promise<BundleResult>;
  /** Bundle every function with bounded concurrency. */
  bundleAll(
    inputs: BundleInput[],
    opts?: { concurrency?: number },
  ): Promise<BundleResult[]>;
  /** Release esbuild's worker process. Always call from a `try/finally`. */
  dispose(): Promise<void>;
}

/**
 * Construct a bundler. esbuild keeps a long-lived worker subprocess; the
 * caller is responsible for invoking `dispose()` on shutdown. The
 * implementation is intentionally stateless apart from that worker —
 * configuration is captured in the closure.
 */
export function createBundler(opts: BundlerOptions): Bundler {
  const sourcemap = opts.sourcemap ?? "linked";

  // The Deno plugin uses the same Rust resolver as `deno run` (compiled to
  // WASM), so resolution of npm:/jsr:/https:/file: specifiers matches the
  // runtime exactly. Created once and reused across builds.
  // The Rust loader auto-discovers `deno.lock` next to `deno.json` for
  // JSR pinning; no explicit lockPath knob is exposed by the plugin.
  const plugin = denoPlugin({ configPath: opts.configPath });

  const buildOne = async (input: BundleInput): Promise<BundleResult> => {
    const start = performance.now();
    const outfile = join(opts.outDir, `${input.name}.js`);

    let result;
    try {
      result = await esbuild.build({
      // The deno-loader resolver needs absolute file URLs for entrypoints
      // so its specifier matching is unambiguous on Windows (where naked
      // paths can be interpreted as relative).
      entryPoints: [pathToFileURL(input.entrypoint).href],
      outfile,
      plugins: [plugin],
      bundle: true,
      format: "esm",
      // Workerd targets a modern V8 — no need to down-level for IE11 etc.
      // Matches Cloudflare's documented baseline; tightening this further
      // (e.g. ES2022) caused regressions with some JSR packages historically.
      target: "es2022",
      platform: "neutral",
      // Prefer browser/import conditions over node so packages with both
      // entrypoints (`@supabase/supabase-js` etc.) pick the leaner ESM
      // build. `node` is added so `node:`-prefixed imports resolve into
      // workerd's nodejs_compat polyfills.
      conditions: ["worker", "browser", "import", "default"],
      banner: { js: BANNER },
      footer: { js: FOOTER },
      sourcemap,
      minify: opts.minify ?? false,
      // Tree-shaking is only safe when imports are pure — esbuild assumes
      // this for `format: esm`. Leave at default (true) so unused npm
      // surface (e.g. server-only Supabase code paths) is dropped.
      treeShaking: true,
      // Emit deterministic output regardless of CWD so the cache is
      // content-comparable across machines.
      absWorkingDir: opts.outDir,
      // We don't want esbuild to log to stdout — the host gateway controls
      // logging surface. Errors are surfaced via thrown exceptions.
      logLevel: "silent",
      // Workerd accepts standard ESM; explicit `mainFields` keeps esbuild
      // honest if a package overrides condition resolution.
      mainFields: ["module", "main"],
      });
    } catch (err) {
      // esbuild throws on any build error with `logLevel: silent`. Re-raise
      // with the function name baked in so the operator immediately knows
      // which function broke without scanning the (potentially huge)
      // esbuild diagnostic block.
      const cause = err instanceof Error ? err.message : String(err);
      throw new Error(
        `workerd bundle failed for function "${input.name}" (${input.entrypoint})\n${cause}`,
        { cause: err instanceof Error ? err : undefined },
      );
    }

    const stat = await Deno.stat(outfile);
    const sourcemapPath = sourcemap === "linked" ? `${outfile}.map` : null;

    return {
      name: input.name,
      bundlePath: outfile,
      sourcemapPath,
      byteLength: stat.size,
      durationMs: performance.now() - start,
    };
  };

  return {
    async bundle(input) {
      await ensureDir(opts.outDir);
      return await buildOne(input);
    },
    async bundleAll(inputs, runOpts = {}) {
      await ensureDir(opts.outDir);
      // Bounded concurrency keeps esbuild from spawning a separate worker
      // for every function; on a 50-function project the default 4
      // saturates a modern laptop without thrashing.
      const concurrency = Math.max(1, runOpts.concurrency ?? 4);
      const results: BundleResult[] = new Array(inputs.length);
      let cursor = 0;
      const workers = Array.from(
        { length: Math.min(concurrency, inputs.length) },
        async () => {
          while (true) {
            const i = cursor++;
            if (i >= inputs.length) return;
            results[i] = await buildOne(inputs[i]);
          }
        },
      );
      await Promise.all(workers);
      return results;
    },
    async dispose() {
      // esbuild keeps a global worker process for the whole runtime.
      // Calling stop() releases it so the host process can exit cleanly.
      await esbuild.stop();
    },
  };
}

/**
 * Convenience: discover function entrypoints under `functionsDir` (one
 * subdirectory per function, each containing `index.ts`) and return the
 * canonical `BundleInput[]`. Mirrors `src/discovery.ts` filtering rules so
 * the workerd backend sees the same function set as the Deno backend.
 */
export async function discoverEntrypoints(
  functionsDir: string,
): Promise<BundleInput[]> {
  const root = resolvePath(functionsDir);
  const out: BundleInput[] = [];
  for await (const entry of Deno.readDir(root)) {
    if (!entry.isDirectory) continue;
    if (entry.name.startsWith("_") || entry.name.endsWith("_shared")) continue;
    const indexPath = join(root, entry.name, "index.ts");
    try {
      const stat = await Deno.stat(indexPath);
      if (!stat.isFile) continue;
    } catch {
      continue;
    }
    out.push({ name: entry.name, entrypoint: indexPath });
  }
  out.sort((a, b) => a.name.localeCompare(b.name));
  return out;
}
