/**
 * Edge-function bundler for the workerd backend.
 *
 * Workerd does not resolve `npm:`, `jsr:`, or `https:` specifiers at runtime
 * — every module must be present on disk as a fully-resolved ESM file before
 * the worker boots. This bundler fills that gap by running esbuild over each
 * function's `index.ts`, with `@luca/esbuild-deno-loader` providing
 * Deno-native specifier resolution. The output is a single self-contained
 * ESM file per function, written to a content-addressed cache directory
 * under the project so repeated boots are fast and reproducible.
 *
 * Each bundle is wrapped to bridge two impedance mismatches:
 *
 *  1. **`Deno.env` shim.** User code reads env via `Deno.env.get(...)`.
 *     Workerd injects environment as the per-request `env` binding instead.
 *     The wrapper installs a `globalThis.Deno.env` proxy that reads from a
 *     module-scope variable refreshed on every dispatch.
 *
 *  2. **`serve()` registry shim.** The 1tube `_shared/handler.ts` shim looks
 *     for `globalThis.__edgeFunctionRegistry` and registers its handler
 *     there at import time. The wrapper supplies a tiny single-handler
 *     registry so the existing shim works unchanged, then exports a workerd
 *     `default { fetch(req, env, ctx) }` that dispatches to whatever the
 *     module registered.
 *
 * The auth boundary stays in 1tube's gateway. For non-public handlers the
 * gateway validates the JWT and forwards the verified identity to workerd
 * via `X-1tube-Auth-*` headers (loopback-only socket). The wrapper
 * reconstructs the `AuthContext` shape from those headers so user code is
 * agnostic to which backend is running.
 *
 * This module is pure I/O orchestration around esbuild. The Deno test
 * suite drives it with real bundles against the playground fixtures —
 * there is no mock layer because esbuild's behaviour is the contract.
 */

import { dirname, join, resolve as resolvePath } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { ensureDir } from "jsr:@std/fs@^1/ensure-dir";
import * as esbuild from "npm:esbuild@^0.28";
import { denoPlugin } from "jsr:@deno/esbuild-plugin@^1.2";
import {
  SHARED_RUNTIME_TOKEN_ENV,
  SHARED_RUNTIME_URL_ENV,
  type SharedRuntimeModule,
} from "./shared-runtime.ts";

/**
 * Banner injected at the top of every bundle. Runs before any user code so
 * top-level `serve(...)` calls find a registry to register against.
 *
 * The captured handler/options live in module scope; the footer below
 * exports the workerd default fetch handler that calls into them.
 *
 * `__1tubeWorkerEnv` is refreshed by the footer on every fetch so
 * `Deno.env.get()` returns the right values for that invocation. Workerd
 * doesn't change `env` per-request in practice (it's bound at boot), but
 * pinning it on each call makes the contract robust to future bindings.
 */
const BANNER = `// AUTO-GENERATED by 1tube workerd bundler — do not edit
import { AsyncLocalStorage as __1tubeAsyncLocalStorage } from "node:async_hooks";
let __1tubeCapturedHandler;
let __1tubeCapturedOpts = { public: false };
let __1tubeWorkerEnv = {};

// ---------------------------------------------------------------------------
// Console capture.
//
// workerd has no message channel back to the gateway, but its stdout is
// already pumped line-by-line into the gateway process. Each console
// call is serialized as ONE marked JSON line; the gateway's log sink
// (src/logs/console-marker.ts) parses marked lines into structured log
// rows and prints the plain message for the operator. The footer runs
// every dispatch inside __1tubeInvocationCtx so concurrent requests
// attribute their lines correctly.
// ---------------------------------------------------------------------------
const __1tubeInvocationCtx = new __1tubeAsyncLocalStorage();
const __1tubeLogMarker = "__1TUBE_LOG__";
const __1tubeRawConsoleLog = console.log.bind(console);
// Like the Deno shim below: only take over console under real workerd.
// When a bundle is imported into a host Deno realm (1tube's own tests)
// the test runner's console must stay untouched.
const __1tubeConsoleCaptureActive = typeof Deno === "undefined";

function __1tubeFormatArg(a) {
  if (typeof a === "string") return a;
  if (a instanceof Error) return a.stack || (a.name + ": " + a.message);
  try {
    const s = JSON.stringify(a);
    if (typeof s === "string") return s;
  } catch { /* circular / bigint — fall through */ }
  try { return String(a); } catch { return "[unprintable]"; }
}

function __1tubeEmitConsole(level, args) {
  if (!__1tubeConsoleCaptureActive) {
    __1tubeRawConsoleLog(...args);
    return;
  }
  try {
    let msg = args.map(__1tubeFormatArg).join(" ");
    if (msg.length > 8192) msg = msg.slice(0, 8192) + "…";
    __1tubeRawConsoleLog(__1tubeLogMarker + JSON.stringify({
      id: __1tubeInvocationCtx.getStore()?.invocationId ?? null,
      level,
      msg,
      ts: Date.now(),
    }));
  } catch { /* capture must never break user code */ }
}

if (__1tubeConsoleCaptureActive) {
  for (const __1tubeLevel of ["debug", "log", "info", "warn", "error"]) {
    console[__1tubeLevel] = (...args) => __1tubeEmitConsole(__1tubeLevel, args);
  }
}

const __1tubeRegistry = {
  register(handler, opts) {
    __1tubeCapturedHandler = handler;
    __1tubeCapturedOpts = { public: !!opts?.public, timeoutMs: opts?.timeoutMs };
  },
};

const __1tubeDenoEnv = {
  get(key) {
    const v = __1tubeWorkerEnv?.[key];
    if (typeof v === "string") return v;
    const pv = globalThis.process?.env?.[key];
    return typeof pv === "string" ? pv : undefined;
  },
  set() {
    throw new Error("Deno.env.set is not supported under the workerd backend");
  },
  delete() {
    throw new Error("Deno.env.delete is not supported under the workerd backend");
  },
  has(key) {
    return typeof __1tubeWorkerEnv?.[key] === "string" ||
      typeof globalThis.process?.env?.[key] === "string";
  },
  toObject() {
    const out = {};
    for (const k of Object.keys(globalThis.process?.env ?? {})) {
      const v = globalThis.process.env[k];
      if (typeof v === "string") out[k] = v;
    }
    for (const k of Object.keys(__1tubeWorkerEnv ?? {})) {
      const v = __1tubeWorkerEnv[k];
      if (typeof v === "string") out[k] = v;
    }
    return out;
  },
};

// __edgeFunctionRegistry is *always* replaced with this bundle's own
// instance. Each bundle has its own module-scope \`__1tubeCapturedHandler\`,
// so the registry's \`register()\` must close over THIS bundle's locals —
// even if a previous import (e.g. when several bundles are imported into
// the same Deno realm during tests) already installed its own.
globalThis.__edgeFunctionRegistry = __1tubeRegistry;

// Install the \`Deno\` shim only when there is no host Deno — i.e. we're
// running under real workerd. Under host Deno (e.g. when 1tube's own
// test suite imports a bundle to verify the bundler) we deliberately
// leave the host's \`Deno\` global untouched: replacing it would break
// the test runner's own use of Deno.makeTempDir / Deno.readDir / etc.
// The runtime contract for the env shim is exercised by the workerd
// end-to-end test, which runs inside an actual workerd process where
// \`typeof Deno === "undefined"\`.
if (typeof Deno === "undefined") {
  Object.defineProperty(globalThis, "Deno", {
    value: {
      env: __1tubeDenoEnv,
      // Defence in depth: a stray top-level Deno.serve(...) becomes a
      // no-op instead of a ReferenceError. The registry is the supported
      // path; this just keeps the failure mode quiet.
      serve: () => ({
        finished: Promise.resolve(),
        shutdown: () => {},
        ref: () => {},
        unref: () => {},
      }),
    },
    writable: true,
    configurable: true,
    enumerable: false,
  });
}
`;

/**
 * Footer injected at the bottom of every bundle. Exports the workerd
 * default handler. Authentication is the gateway's job; this just rebuilds
 * the AuthContext from the trusted internal headers the gateway forwards.
 */
const FOOTER = `
function __1tubeBuildAuth(request) {
  const h = request.headers;
  const payloadRaw = h.get("X-1tube-Auth-Payload");
  let payload = {};
  if (payloadRaw) {
    try { payload = JSON.parse(payloadRaw); } catch { payload = {}; }
  }
  return {
    userId: h.get("X-1tube-Auth-User") || "anon",
    email: h.get("X-1tube-Auth-Email") || "",
    rawToken: h.get("X-1tube-Auth-Token") || "",
    payload,
  };
}

export default {
  async fetch(request, env, _ctx) {
    __1tubeWorkerEnv = env || {};
    if (typeof __1tubeCapturedHandler !== "function") {
      return new Response(
        JSON.stringify({ error: "function did not register a handler" }),
        { status: 500, headers: { "content-type": "application/json" } },
      );
    }
    // Invocation id stamped by the gateway before proxying. Binds this
    // dispatch's console output (see the banner's console shim) to the
    // invocation row the gateway persists.
    const __1tubeInvocationId = request.headers.get("x-1tube-invocation-id");
    const __1tubeRun = async () => {
      if (__1tubeCapturedOpts.public) {
        return await __1tubeCapturedHandler(request);
      }
      return await __1tubeCapturedHandler(request, __1tubeBuildAuth(request));
    };
    try {
      return await __1tubeInvocationCtx.run(
        { invocationId: __1tubeInvocationId },
        __1tubeRun,
      );
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      // Surface the stack through the capture channel so the log store
      // keeps it next to the invocation that threw.
      __1tubeInvocationCtx.run({ invocationId: __1tubeInvocationId }, () => {
        __1tubeEmitConsole("error", [err instanceof Error ? (err.stack || msg) : msg]);
      });
      return new Response(
        JSON.stringify({ error: msg }),
        { status: 500, headers: { "content-type": "application/json" } },
      );
    }
  },
};
`;

export interface BundleInput {
  /** Logical function name (used as bundle filename and in capnp config). */
  name: string;
  /** Absolute path to the function's `index.ts` entrypoint. */
  entrypoint: string;
}

export interface BundleResult {
  /** Same as input. */
  name: string;
  /** Absolute path to the produced `.js` bundle. */
  bundlePath: string;
  /** Absolute path to the produced sourcemap, or null when sourcemaps are off. */
  sourcemapPath: string | null;
  /** Bundle byte size — useful for diagnostics and CI assertions. */
  byteLength: number;
  /** Wall-clock time esbuild spent on this function. */
  durationMs: number;
}

export interface ChunkedBundleChunk {
  /** Manifest-relative POSIX path, e.g. `chunks/chunk-ABC123.js`. */
  file: string;
  /** Absolute path to the emitted chunk file. */
  path: string;
  /** Chunk byte size after chunk-only minification. */
  byteLength: number;
  /** Chunk byte size before chunk-only minification. */
  originalByteLength: number;
}

export interface ChunkedBundleResult extends BundleResult {
  /** Manifest-relative POSIX module files required by this worker, entry first. */
  moduleFiles: string[];
  /** Entry module byte size before entry-only minification. */
  originalByteLength: number;
}

export interface ChunkedBundleAllResult {
  functions: ChunkedBundleResult[];
  chunks: ChunkedBundleChunk[];
  entryMinification: {
    preBytes: number;
    postBytes: number;
  };
  chunkMinification: {
    preBytes: number;
    postBytes: number;
  };
}

export interface WorkerdSharedModuleInput {
  /** Stable id used in the generated RPC path and prebuilt manifest. */
  id: string;
  /** Absolute source module path on disk. */
  sourcePath: string;
  /** Exported functions to expose through the shared runtime. */
  exportNames: readonly string[];
}

export interface BundlerOptions {
  /**
   * Directory to write bundles into. Files are named `<name>.js` (+
   * `<name>.js.map` when `sourcemap` is true). Created if missing.
   */
  outDir: string;
  /**
   * Path to the host project's `deno.json` so esbuild-deno-loader can pick
   * up the import map. Optional — when omitted no import map is applied.
   */
  configPath?: string;
  /**
   * Enable inline sourcemaps (`true`), separate `.map` files (`"linked"`),
   * or disable (`false`). Defaults to `"linked"` for production-style
   * debugging without bloating the bundle.
   */
  sourcemap?: boolean | "linked" | "inline";
  /** Emit minified output. Defaults to false (keeps readable stack traces). */
  minify?: boolean;
  /**
   * Modules that should be owned by the gateway process, not by each
   * workerd isolate. Imports that resolve to one of these source paths
   * are replaced with generated RPC stubs.
   */
  sharedModules?: readonly WorkerdSharedModuleInput[];
}

/** State held by a long-lived bundler so esbuild can be reused across builds. */
export interface Bundler {
  /** Bundle a single function. */
  bundle(input: BundleInput): Promise<BundleResult>;
  /** Bundle every function with bounded concurrency. */
  bundleAll(
    inputs: BundleInput[],
    opts?: { concurrency?: number },
  ): Promise<BundleResult[]>;
  /** Release esbuild's worker process. Always call from a `try/finally`. */
  dispose(): Promise<void>;
}

export interface SharedBundleResult extends SharedRuntimeModule {
  byteLength: number;
  originalByteLength: number;
  durationMs: number;
}

export async function disposeBundlerResources(): Promise<void> {
  await esbuild.stop();
  // esbuild.stop() tears down the service process synchronously from
  // esbuild's point of view, but Deno's node:child_process shim settles
  // the underlying spawn wait op on the next turn. Let that completion
  // run before sanitizer-enabled tests assert that no child process
  // resources remain.
  await new Promise((resolve) => setTimeout(resolve, 0));
}

function sharedModuleStubSource(module: WorkerdSharedModuleInput): string {
  const exports = module.exportNames.map((name) =>
    `export async function ${name}(...args) {
  return await callShared(${JSON.stringify(name)}, args);
}`
  ).join("\n\n");
  return `
const RUNTIME_URL_ENV = ${JSON.stringify(SHARED_RUNTIME_URL_ENV)};
const RUNTIME_TOKEN_ENV = ${JSON.stringify(SHARED_RUNTIME_TOKEN_ENV)};
const MODULE_ID = ${JSON.stringify(module.id)};

function env(name) {
  const v = globalThis.Deno?.env?.get?.(name) ?? globalThis.process?.env?.[name];
  return typeof v === "string" ? v : "";
}

async function callShared(exportName, args) {
  const base = env(RUNTIME_URL_ENV);
  const token = env(RUNTIME_TOKEN_ENV);
  if (!base || !token) {
    throw new Error("1tube shared runtime is not configured");
  }
  const res = await fetch(
    base + "/modules/" + encodeURIComponent(MODULE_ID) + "/call/" + encodeURIComponent(exportName),
    {
    method: "POST",
    headers: {
      "authorization": "Bearer " + token,
      "content-type": "application/json",
    },
    body: JSON.stringify({ args }),
    },
  );
  const payload = await res.json().catch(() => ({}));
  if (!res.ok) {
    throw new Error(payload?.error || "1tube shared runtime request failed");
  }
  return payload.value;
}

${exports}
`;
}

function importerToPath(importer: string): string | null {
  if (!importer) return null;
  try {
    if (importer.startsWith("file:")) return fileURLToPath(importer);
    return importer;
  } catch {
    return null;
  }
}

function resolveLocalImport(args: esbuild.OnResolveArgs): string | null {
  if (
    !args.path.startsWith(".") && !args.path.startsWith("/") &&
    !/^[A-Za-z]:[\\/]/.test(args.path)
  ) {
    return null;
  }
  if (args.path.startsWith("/") || /^[A-Za-z]:[\\/]/.test(args.path)) {
    return resolvePath(args.path);
  }
  const importerPath = importerToPath(args.importer);
  if (!importerPath) return null;
  return resolvePath(dirname(importerPath), args.path);
}

function sharedModulesExternalPlugin(
  sharedModules: readonly WorkerdSharedModuleInput[],
): esbuild.Plugin {
  const byPath = new Map(
    sharedModules.map((m) => [resolvePath(m.sourcePath), m]),
  );
  return {
    name: "1tube-shared-modules",
    setup(build) {
      build.onResolve({ filter: /.*/ }, (args) => {
        const resolved = resolveLocalImport(args);
        if (!resolved) return null;
        const mod = byPath.get(resolved);
        if (!mod) return null;
        return { path: mod.id, namespace: "1tube-shared-runtime" };
      });
      build.onLoad(
        { filter: /.*/, namespace: "1tube-shared-runtime" },
        (args) => ({
          contents: sharedModuleStubSource(
            sharedModules.find((m) => m.id === args.path)!,
          ),
          loader: "js",
        }),
      );
    },
  };
}

function patchCjsDefaultInterop(code: string): string {
  // esbuild's default helper intentionally withholds `default` when a
  // CommonJS module sets `__esModule`. That matches Babel-transpiled
  // modules that also provide a real `.default`, but breaks plain CJS
  // packages such as `tslib` whose UMD wrapper sets `__esModule` while
  // only exporting named helpers. Workerd's nodejs_compat behavior is
  // closer to Node's ESM/CJS bridge: a default import from CJS resolves
  // to module.exports. Preserve real default exports, but synthesize one
  // when absent.
  return code.replace(
    'isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,',
    'isNodeMode || !mod || !mod.__esModule || !("default" in mod) ? __defProp(target, "default", { value: mod, enumerable: true }) : target,',
  );
}

const ENTRY_PROXY_NAMESPACE = "1tube-entry-proxy";

function toPosix(path: string): string {
  return path.replace(/\\/g, "/");
}

function entryProxySource(entrypoint: string): string {
  return `${BANNER}
await import(${JSON.stringify(pathToFileURL(entrypoint).href)});
${FOOTER}
`;
}

function entryProxyPlugin(inputs: readonly BundleInput[]): esbuild.Plugin {
  const byName = new Map(inputs.map((input) => [input.name, input]));
  return {
    name: "1tube-entry-proxy",
    setup(build) {
      build.onResolve({ filter: /^1tube-entry-proxy:/ }, (args) => {
        return {
          path: args.path.slice("1tube-entry-proxy:".length),
          namespace: ENTRY_PROXY_NAMESPACE,
        };
      });
      build.onLoad(
        { filter: /.*/, namespace: ENTRY_PROXY_NAMESPACE },
        (args) => {
          const input = byName.get(args.path);
          if (!input) {
            throw new Error(
              `missing 1tube entry proxy input for ${args.path}`,
            );
          }
          return {
            contents: entryProxySource(input.entrypoint),
            loader: "js",
            resolveDir: dirname(input.entrypoint),
          };
        },
      );
    },
  };
}

async function patchOutputFile(path: string): Promise<void> {
  const emitted = await Deno.readTextFile(path);
  const patched = patchCjsDefaultInterop(emitted);
  if (patched !== emitted) {
    await Deno.writeTextFile(path, patched);
  }
}

async function minifyOutputFile(
  path: string,
  sourcemap: boolean | "linked" | "inline",
): Promise<{
  originalByteLength: number;
  byteLength: number;
}> {
  const original = await Deno.readTextFile(path);
  const originalByteLength = new TextEncoder().encode(original).byteLength;
  const result = await esbuild.transform(original, {
    loader: "js",
    format: "esm",
    target: "es2022",
    minify: true,
    legalComments: "none",
    sourcemap: sourcemap === "inline"
      ? "inline"
      : sourcemap === "linked"
      ? "external"
      : false,
    sourcefile: path.split(/[\\/]/).pop() ?? "bundle.js",
  });
  let code = result.code;
  if (sourcemap === "linked" && result.map) {
    const mapPath = `${path}.map`;
    await Deno.writeTextFile(mapPath, result.map);
    code = code.replace(/\n?\/\/# sourceMappingURL=.*$/m, "");
    code += `\n//# sourceMappingURL=${mapPath.split(/[\\/]/).pop()}\n`;
  }
  await Deno.writeTextFile(path, code);
  return {
    originalByteLength,
    byteLength: new TextEncoder().encode(code).byteLength,
  };
}

/**
 * Construct a bundler. esbuild keeps a long-lived worker subprocess; the
 * caller is responsible for invoking `dispose()` on shutdown. The
 * implementation is intentionally stateless apart from that worker —
 * configuration is captured in the closure.
 */
export function createBundler(opts: BundlerOptions): Bundler {
  const sourcemap = opts.sourcemap ?? "linked";

  // The Deno plugin uses the same Rust resolver as `deno run` (compiled to
  // WASM), so resolution of npm:/jsr:/https:/file: specifiers matches the
  // runtime exactly. Created once and reused across builds.
  // The Rust loader auto-discovers `deno.lock` next to `deno.json` for
  // JSR pinning; no explicit lockPath knob is exposed by the plugin.
  const plugin = denoPlugin({ configPath: opts.configPath });
  const sharedModules = opts.sharedModules ?? [];
  const plugins = sharedModules.length > 0
    ? [sharedModulesExternalPlugin(sharedModules), plugin]
    : [plugin];

  const buildOne = async (input: BundleInput): Promise<BundleResult> => {
    const start = performance.now();
    const outfile = join(opts.outDir, `${input.name}.js`);

    try {
      await esbuild.build({
        // The deno-loader resolver needs absolute file URLs for entrypoints
        // so its specifier matching is unambiguous on Windows (where naked
        // paths can be interpreted as relative).
        entryPoints: [pathToFileURL(input.entrypoint).href],
        outfile,
        plugins,
        bundle: true,
        format: "esm",
        // Workerd targets a modern V8 — no need to down-level for IE11 etc.
        // Matches Cloudflare's documented baseline; tightening this further
        // (e.g. ES2022) caused regressions with some JSR packages historically.
        target: "es2022",
        platform: "neutral",
        // Prefer browser/import conditions over node so packages with both
        // entrypoints (`@supabase/supabase-js` etc.) pick the leaner ESM
        // build. `node` is added so `node:`-prefixed imports resolve into
        // workerd's nodejs_compat polyfills.
        conditions: ["worker", "browser", "import", "default"],
        banner: { js: BANNER },
        footer: { js: FOOTER },
        sourcemap,
        minify: opts.minify ?? false,
        // Tree-shaking is only safe when imports are pure — esbuild assumes
        // this for `format: esm`. Leave at default (true) so unused npm
        // surface (e.g. server-only Supabase code paths) is dropped.
        treeShaking: true,
        // Emit deterministic output regardless of CWD so the cache is
        // content-comparable across machines.
        absWorkingDir: opts.outDir,
        // We don't want esbuild to log to stdout — the host gateway controls
        // logging surface. Errors are surfaced via thrown exceptions.
        logLevel: "silent",
        // Workerd accepts standard ESM; explicit `mainFields` keeps esbuild
        // honest if a package overrides condition resolution.
        mainFields: ["module", "main"],
      });
    } catch (err) {
      // esbuild throws on any build error with `logLevel: silent`. Re-raise
      // with the function name baked in so the operator immediately knows
      // which function broke without scanning the (potentially huge)
      // esbuild diagnostic block.
      const cause = err instanceof Error ? err.message : String(err);
      throw new Error(
        `workerd bundle failed for function "${input.name}" (${input.entrypoint})\n${cause}`,
        { cause: err instanceof Error ? err : undefined },
      );
    }

    await patchOutputFile(outfile);

    const stat = await Deno.stat(outfile);
    const sourcemapPath = sourcemap === "linked" ? `${outfile}.map` : null;

    return {
      name: input.name,
      bundlePath: outfile,
      sourcemapPath,
      byteLength: stat.size,
      durationMs: performance.now() - start,
    };
  };

  return {
    async bundle(input) {
      await ensureDir(opts.outDir);
      return await buildOne(input);
    },
    async bundleAll(inputs, runOpts = {}) {
      await ensureDir(opts.outDir);
      // Bounded concurrency keeps esbuild from spawning a separate worker
      // for every function; on a 50-function project the default 4
      // saturates a modern laptop without thrashing.
      const concurrency = Math.max(1, runOpts.concurrency ?? 4);
      const results: BundleResult[] = new Array(inputs.length);
      let cursor = 0;
      const workers = Array.from(
        { length: Math.min(concurrency, inputs.length) },
        async () => {
          while (true) {
            const i = cursor++;
            if (i >= inputs.length) return;
            results[i] = await buildOne(inputs[i]);
          }
        },
      );
      await Promise.all(workers);
      return results;
    },
    async dispose() {
      // esbuild keeps a global worker process for the whole runtime.
      // Calling stop() releases it so the host process can exit cleanly.
      await esbuild.stop();
    },
  };
}

export async function bundleAllChunked(
  opts: BundlerOptions & {
    inputs: BundleInput[];
  },
): Promise<ChunkedBundleAllResult> {
  await ensureDir(opts.outDir);
  const start = performance.now();
  const sourcemap = opts.sourcemap ?? "linked";
  const sharedModules = opts.sharedModules ?? [];
  const plugins = [
    entryProxyPlugin(opts.inputs),
    ...(sharedModules.length > 0
      ? [sharedModulesExternalPlugin(sharedModules)]
      : []),
    denoPlugin({ configPath: opts.configPath }),
  ];
  const entryPoints = Object.fromEntries(
    opts.inputs.map((input) => [input.name, `1tube-entry-proxy:${input.name}`]),
  );

  let result: esbuild.BuildResult<{
    metafile: true;
    write: true;
  }>;
  try {
    result = await esbuild.build({
      entryPoints,
      outdir: opts.outDir,
      plugins,
      bundle: true,
      splitting: true,
      format: "esm",
      target: "es2022",
      platform: "neutral",
      conditions: ["worker", "browser", "import", "default"],
      sourcemap,
      minify: opts.minify ?? false,
      treeShaking: true,
      absWorkingDir: opts.outDir,
      logLevel: "silent",
      mainFields: ["module", "main"],
      entryNames: "functions/[name]",
      chunkNames: "chunks/[name]-[hash]",
      metafile: true,
      write: true,
    });
  } catch (err) {
    const cause = err instanceof Error ? err.message : String(err);
    throw new Error(`workerd chunked bundle failed\n${cause}`, {
      cause: err instanceof Error ? err : undefined,
    });
  }

  const outputs = result.metafile.outputs;
  const entryByName = new Map<string, string>();
  const importsByOutput = new Map<string, string[]>();
  for (const [outputPath, output] of Object.entries(outputs)) {
    if (!outputPath.endsWith(".js")) continue;
    const rel = toPosix(outputPath);
    importsByOutput.set(
      rel,
      output.imports
        .filter((i) => i.path.endsWith(".js"))
        .map((i) => toPosix(i.path)),
    );
    if (output.entryPoint) {
      const match = output.entryPoint.match(/^1tube-entry-proxy:(.+)$/);
      if (match) entryByName.set(match[1], rel);
    }
  }

  const collectReachable = (entry: string): string[] => {
    const seen = new Set<string>();
    const out: string[] = [];
    const visit = (file: string) => {
      if (seen.has(file)) return;
      seen.add(file);
      out.push(file);
      for (const dep of importsByOutput.get(file) ?? []) visit(dep);
    };
    visit(entry);
    return out;
  };

  const emittedJs = Object.keys(outputs)
    .map(toPosix)
    .filter((file) => file.endsWith(".js"));
  await Promise.all(
    emittedJs.map((file) => patchOutputFile(join(opts.outDir, file))),
  );
  const minifiedSizesByFile = new Map<string, {
    originalByteLength: number;
    byteLength: number;
  }>();
  await Promise.all(
    emittedJs.map(async (file) => {
      minifiedSizesByFile.set(
        file,
        await minifyOutputFile(join(opts.outDir, file), sourcemap),
      );
    }),
  );

  const chunkFiles = emittedJs
    .filter((file) => file.startsWith("chunks/"))
    .sort();
  const chunks: ChunkedBundleChunk[] = chunkFiles.map((file) => {
    const path = join(opts.outDir, file);
    const sizes = minifiedSizesByFile.get(file);
    if (!sizes) {
      throw new Error(
        `workerd chunked bundle missing minified size for ${file}`,
      );
    }
    return {
      file,
      path,
      byteLength: sizes.byteLength,
      originalByteLength: sizes.originalByteLength,
    };
  });
  const chunkMinification = chunks.reduce(
    (acc, chunk) => {
      acc.preBytes += chunk.originalByteLength;
      acc.postBytes += chunk.byteLength;
      return acc;
    },
    { preBytes: 0, postBytes: 0 },
  );
  const entryMinification = [...entryByName.values()].reduce(
    (acc, entry) => {
      const sizes = minifiedSizesByFile.get(entry);
      if (sizes) {
        acc.preBytes += sizes.originalByteLength;
        acc.postBytes += sizes.byteLength;
      }
      return acc;
    },
    { preBytes: 0, postBytes: 0 },
  );

  const durationMs = performance.now() - start;
  const functions: ChunkedBundleResult[] = [];
  for (const input of opts.inputs) {
    const entry = entryByName.get(input.name);
    if (!entry) {
      throw new Error(
        `workerd chunked bundle missing entry output for ${input.name}`,
      );
    }
    const bundlePath = join(opts.outDir, entry);
    const sizes = minifiedSizesByFile.get(entry);
    if (!sizes) {
      throw new Error(
        `workerd chunked bundle missing minified size for ${entry}`,
      );
    }
    functions.push({
      name: input.name,
      bundlePath,
      sourcemapPath: sourcemap === "linked" ? `${bundlePath}.map` : null,
      byteLength: sizes.byteLength,
      durationMs: durationMs / Math.max(1, opts.inputs.length),
      moduleFiles: collectReachable(entry),
      originalByteLength: sizes.originalByteLength,
    });
  }

  return { functions, chunks, entryMinification, chunkMinification };
}

export async function bundleSharedModule(opts: {
  module: WorkerdSharedModuleInput;
  outDir: string;
  configPath?: string;
  minify?: boolean;
}): Promise<SharedBundleResult> {
  await ensureDir(opts.outDir);
  const start = performance.now();
  const outfile = join(opts.outDir, `${opts.module.id}.js`);
  await esbuild.build({
    entryPoints: [pathToFileURL(opts.module.sourcePath).href],
    outfile,
    plugins: [denoPlugin({ configPath: opts.configPath })],
    bundle: true,
    format: "esm",
    target: "es2022",
    platform: "neutral",
    conditions: ["worker", "browser", "import", "default"],
    sourcemap: false,
    minify: opts.minify ?? false,
    treeShaking: true,
    absWorkingDir: opts.outDir,
    logLevel: "silent",
    mainFields: ["module", "main"],
  });
  await patchOutputFile(outfile);
  const sizes = await minifyOutputFile(outfile, false);
  return {
    id: opts.module.id,
    bundlePath: outfile,
    exportNames: opts.module.exportNames,
    byteLength: sizes.byteLength,
    originalByteLength: sizes.originalByteLength,
    durationMs: performance.now() - start,
  };
}

function moduleIdFromPath(path: string): string {
  const base = path.split(/[\\/]/).pop() ?? "shared";
  return base.replace(/\.[^.]+$/, "").replace(/[^A-Za-z0-9_-]/g, "-");
}

function extractExportedFunctionNames(source: string): string[] {
  const names = new Set<string>();
  for (
    const match of source.matchAll(
      /export\s+(?:async\s+)?function\s+([A-Za-z_$][\w$]*)\s*\(/g,
    )
  ) {
    names.add(match[1]);
  }
  for (
    const match of source.matchAll(
      /export\s+const\s+([A-Za-z_$][\w$]*)\s*=\s*(?:async\s*)?\(/g,
    )
  ) {
    names.add(match[1]);
  }
  for (
    const match of source.matchAll(
      /export\s+const\s+([A-Za-z_$][\w$]*)\s*=\s*async\s+/g,
    )
  ) {
    names.add(match[1]);
  }
  return [...names].sort();
}

async function maybeSharedModule(
  path: string,
): Promise<WorkerdSharedModuleInput | null> {
  try {
    const stat = await Deno.stat(path);
    if (!stat.isFile) return null;
    const source = await Deno.readTextFile(path);
    const exportNames = extractExportedFunctionNames(source);
    if (exportNames.length === 0) {
      throw new Error(`shared module ${path} does not export any functions`);
    }
    return {
      id: moduleIdFromPath(path),
      sourcePath: resolvePath(path),
      exportNames,
    };
  } catch (err) {
    if (err instanceof Deno.errors.NotFound) return null;
    throw err;
  }
}

export async function discoverSharedModules(
  functionsDir: string,
  explicitPaths: readonly string[] = [],
): Promise<WorkerdSharedModuleInput[]> {
  const root = resolvePath(functionsDir);
  const candidates = explicitPaths.length > 0
    ? explicitPaths.map((p) =>
      /^[A-Za-z]:[\\/]/.test(p) || p.startsWith("/") ? p : resolvePath(root, p)
    )
    : [];

  // Built-in convention: if a Supabase-style profile cache exists, run
  // it as a gateway-owned shared module unless the caller already named it.
  const defaultProfile = join(root, "_shared", "profile-cache.ts");
  if (!candidates.some((p) => resolvePath(p) === resolvePath(defaultProfile))) {
    candidates.push(defaultProfile);
  }

  const out: WorkerdSharedModuleInput[] = [];
  const seen = new Set<string>();
  for (const candidate of candidates) {
    const resolved = resolvePath(candidate);
    if (seen.has(resolved)) continue;
    seen.add(resolved);
    const mod = await maybeSharedModule(resolved);
    if (mod) out.push(mod);
  }
  return out;
}

/**
 * Convenience: discover function entrypoints under `functionsDir` (one
 * subdirectory per function, each containing `index.ts`) and return the
 * canonical `BundleInput[]`. Mirrors `src/discovery.ts` filtering rules so
 * the workerd backend sees the same function set as the Deno backend.
 */
export async function discoverEntrypoints(
  functionsDir: string,
): Promise<BundleInput[]> {
  const root = resolvePath(functionsDir);
  const out: BundleInput[] = [];
  for await (const entry of Deno.readDir(root)) {
    if (!entry.isDirectory) continue;
    if (entry.name.startsWith("_") || entry.name.endsWith("_shared")) continue;
    const indexPath = join(root, entry.name, "index.ts");
    try {
      const stat = await Deno.stat(indexPath);
      if (!stat.isFile) continue;
    } catch {
      continue;
    }
    out.push({ name: entry.name, entrypoint: indexPath });
  }
  out.sort((a, b) => a.name.localeCompare(b.name));
  return out;
}
